version: "3"
services:
  nginx:
    image: nginx:1.15.1-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../www/public:/var/www/html/public:rw
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
      - ../logs/nginx:/var/log/nginx:rw
    networks:
      - net-php
    restart: always
    command: nginx -g 'daemon off;'

  php:
    image: registry.cn-qingdao.aliyuncs.com/php_fpm/5.6.37:v1
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ../www:/var/www/html:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ../logs/php:/usr/local/var/log:rw
    networks:
      - net-php
      - net-mysql
      - net-redis
    restart: always
    command: php-fpm

  mysql:
    image: mysql:5.6.40
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ../data/mysql:/var/lib/mysql:rw
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: eshop
      MYSQL_USER: djs
      MYSQL_PASSWORD: 111111
    restart: always
    command: "--character-set-server=utf8"

  redis:
    image: redis:3.2.11-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data:rw
    networks:
      - net-redis
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    networks:
      - net-mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

networks:
  net-php:
  net-mysql:
  net-redis:
